### ISSUE TITLE
Первичная настройка проекта

### ISSUE THREAD

**Issue by raantoniv** [openworld-community/rzrbs-vacancy-bot#1]

**Comment by marylorian** [comment]
первоначальная конфигурация добавлена в коммите - https://github.com/openworld-community/rzrbs-vacancy-bot/commit/32d9f245647b23f3ed9b64e4f35496249c8db966

- Prettier
- Linter
- TypeScript
- Git Hooks
- Telegraf

**Comment by marylorian** [comment]
первоначальная конфигурация добавлена в коммите - https://github.com/openworld-community/rzrbs-vacancy-bot/commit/32d9f245647b23f3ed9b64e4f35496249c8db966

- Prettier
- Linter
- TypeScript
- Git Hooks
- Telegraf
