### ISSUE TITLE
Реализовать отзыв вакансии

### ISSUE THREAD

**Issue by raantoniv** [openworld-community/rzrbs-vacancy-bot#5]

**Comment by marylorian** [comment]
сейчас флоу следующий:
Юзер нажимает на "Опубликовать", 
<img width="746" alt="Screenshot 2023-05-20 at 01 20 04" src="https://github.com/openworld-community/rzrbs-vacancy-bot/assets/33313053/5320ef9f-a8ea-47d9-b521-a74f75443b78">

сет кнопок меняется на "Редактировать" и "Отозвать", Юзер нажимает "Отозвать", 
<img width="746" alt="Screenshot 2023-05-20 at 01 20 13" src="https://github.com/openworld-community/rzrbs-vacancy-bot/assets/33313053/6dc8c3f9-6d1e-42a4-9ad8-156a18823ab2">

кнопки пропадают, перед текстом вакансии появляется "[ОТОЗВАНО]"
<img width="746" alt="Screenshot 2023-05-20 at 01 20 17" src="https://github.com/openworld-community/rzrbs-vacancy-bot/assets/33313053/ee287e29-8910-4107-9b4d-5513c258e3ad">
