### ISSUE TITLE
Реализовать автоматическое управление расписанием публикации

### ISSUE THREAD

**Issue by raantoniv** [openworld-community/rzrbs-vacancy-bot#6]
Как владелец канала я хочу установить лимит публикаций вакансий в день, время начала и окончания периода публикации.
По умолчанию: 2 вакансии в день (с пн по пт), с 10:00 по 18:00 (МСК) с интервалом в 5 часов.

В случае большого пула вакансий автоматически уменьшить интервал публикаций, минимальный интервал - 2 часа.
Пул рассчитывается на 2 недели. Если количество публикаций невозможно разместить за весь этот период, то публикации расчитываются с новым уменьшенным интервалом.

В случае невозможности размещения всех публикаций в 2х недельный период даже с минимальным интервалом, публикация записывается в следующий пул.

**Comment by marylorian** [comment]
В текущей имплементации https://github.com/openworld-community/rzrbs-vacancy-bot/pull/32:

- Лимит вакансий, которые могут быть опубликованы за день, устанавливается в переменную `DAILY_VACANCY_LIMIT` (указывается целым числом)
- График работы устанавливается в `PUBLISH_CONFIG` в формате JSON - `{ "week day short name": [start hour, end hour] }`
- Интервал публикации вакансий записывается в `PUBLISH_INTERVAL` (указывается целым числом в часах)
- Минимальный интервал вакансий, до которого мы можем снижать стандартный интервал, устанавливается в `MIN_PUBLISH_INTERVAL` (указывается целым числом в часах)
- Лимит вакансий, которые могут быть опубликованы одним юзером за месяц, устанавливается в `USER_MONTH_VACANCY_LIMIT` (целое число)

То есть текущую логику из описания можно описать с помощью добавления следующих значений в `.env` файл:
```
MIN_PUBLISH_INTERVAL=2
PUBLISH_INTERVAL=5
USER_MONTH_VACANCY_LIMIT=2
DAILY_VACANCY_LIMIT=2
PUBLISH_CONFIG='{ "mon": [10,18], "tue": [10,18], "wed": [10,18], "thu": [10,18], "fri": [10,18] }'
```

Пул вакансий пересчитывается каждый раз в начале рабочего дня
