### ISSUE TITLE
Конфигурация сборки образа приложения

### ISSUE THREAD

**Issue by raantoniv** [openworld-community/rzrbs-vacancy-bot#7]

**Comment by NazarVasyliv** [comment]
Пулл реквест ветки Devops. 
Для локальной отладки должно хватить.
Вчера обсуждали смену базы, в реквесте подключение к базе mongo.
Параметры необходимые забиваются в .env_docker.
Сборка по докерфайлу у меня прошла, если работает некорректно, то прошу сказать с указанием какие ошибки выходят и как запускаете.

**Comment by NazarVasyliv** [comment]
Из docker-compose убран mongo и строки подключение к монго.
В Dockerfile добавлена возможность подключаться к базе postgres в облаке.
Добавлен .env.example со строкой подключения к postgres в облаке.
В readme добавлено описания разворачивания docker-compose.
